# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9345240ef8db70dd0bc7a983b6ea88ff"
application_url = "https://nominations-cleaner-toronto-vsnet.trycloudflare.com"
embedded = true
name = "BD-challenge-NM"
handle = "bd-challenge-nm"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://nominations-cleaner-toronto-vsnet.trycloudflare.com/auth/callback",
  "https://nominations-cleaner-toronto-vsnet.trycloudflare.com/auth/shopify/callback",
  "https://nominations-cleaner-toronto-vsnet.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
